all:
  children:
    company-a:
      hosts:
        A-EDGE-ISP-1:
        A-EDGE-ISP-2:
        A-CORE:
    company-b:
      hosts:
        B-EDGE-ISP-1:
        B-EDGE-ISP-2:
        B-CORE:
    isp:
      hosts:
        ISP-1:
        ISP-2:
