all:
  children:
    network:
      hosts:
        syria:
        lebanon:
        egypt:
        USA:
    US:
      hosts:
        USA:
    GO:
      hosts:
        google:
    #dhcp:
      #hosts:
        #syria:
        #egypt:
    wg:
      hosts:
        syria:
        jordan:
        iraq:
    bgp:
      hosts:
        mexico:
        kanada:
        USA:
        syria:
        lebanon:
        egypt:
        amazon:
        google:
