all:
  children:
    routeros:
      hosts:
        CCR2004-16G-2S-core:
        CCR2004-16G-2S-pppoe_server:
    client:
      hosts:
        CCR2004-16G-2S-pppoe_client_1:
        CCR2004-16G-2S-pppoe_client_2:
